### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by Zikot4** [daxterstroll/RoR#1]
1 https://github.com/daxterstroll/RoR/blob/69a07089468fb241f5c95ebb2382ec84121c8968/app/controllers/items_controller.rb#L2
use new style array of symbol since ruby 1.9
https://github.com/bbatsov/ruby-style-guide#percent-i

2. again about validation

https://github.com/daxterstroll/RoR/blob/69a07089468fb241f5c95ebb2382ec84121c8968/app/models/review.rb#L10
why so difficult? 

3  boolean == boolean
https://github.com/daxterstroll/RoR/blob/69a07089468fb241f5c95ebb2382ec84121c8968/app/models/review.rb#L13
very popular mistake 

and one more, you can remove ternary operator here

4 https://github.com/daxterstroll/RoR/commit/c611318489c749179d26a59cdae05793c059bbbe#r29057500

**Comment by daxterstroll** [comment]
1.done
2. left to fix Users
3.done
4.done
